// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACpH9ludsGsOc54pI8nebl-Ay2C-RDJzk',
    appId: '1:1065645902705:web:2081393c9cf65942bd44d0',
    messagingSenderId: '1065645902705',
    projectId: 'grids-bramp-net',
    authDomain: 'grids-bramp-net.firebaseapp.com',
    storageBucket: 'grids-bramp-net.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-GjGm1_kkxY_MIT_GZ9vOBK3RVf7KHQ',
    appId: '1:1065645902705:android:4dfe7974da17d586bd44d0',
    messagingSenderId: '1065645902705',
    projectId: 'grids-bramp-net',
    storageBucket: 'grids-bramp-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfklHLZWlG4dVJg4kZnDlX2QRhEkW7XqM',
    appId: '1:1065645902705:ios:668fff455a8269bbbd44d0',
    messagingSenderId: '1065645902705',
    projectId: 'grids-bramp-net',
    storageBucket: 'grids-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.grids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfklHLZWlG4dVJg4kZnDlX2QRhEkW7XqM',
    appId: '1:1065645902705:ios:668fff455a8269bbbd44d0',
    messagingSenderId: '1065645902705',
    projectId: 'grids-bramp-net',
    storageBucket: 'grids-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.grids',
  );
}
