name: grids
description: "Grids — a puzzle game."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  grids_engine:
    path: ../../packages/engine

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  clock: ^1.1.2
  go_router: ^17.1.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_widget_from_html_core: ^0.17.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.2.0
  widgetbook: ^3.22.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/ripple_distortion.frag

  assets:
    - web/privacy.html

flutter_native_splash:
  color: "#0D0E15"
  web: true
  android: true
  ios: true
